### ISSUE TITLE
Async method calling a dependency synchronously?

### ISSUE THREAD

**Issue by nelsonic** [jonschlinkert/dirs#1] opened 2015-03-21 16:54 UTC
Hi @jonschlinkert, hope you are well.

While trying out this module, we noticed that you are calling your [**is-directory**](https://github.com/jonschlinkert/is-directory/blob/master/index.js#L19) module's `isDir` method (_without_ a callback) in the `dirs` (async) method on line **31**:
https://github.com/jonschlinkert/dirs/blob/c90b488ab49bb07e51d0653bdf347ee17d3eb67a/index.js#L31

am I missing something...?
Thanks!

**Comment by jonschlinkert** [comment] 2015-03-21 20:02
nope you're right. initially is-directory was sync only: https://github.com/jonschlinkert/is-directory/commit/8989e5e4eb4d9452f94d3234773cbb6252f8d90a. Looks like I did both on the same day and forgot to circle back to this lib to update for async.

thanks for the heads up!

**Comment by jonschlinkert** [comment] 2015-03-22 01:54
actually, yes, I forgot about this until I pulled it down: https://github.com/jonschlinkert/dirs/blob/c90b488ab49bb07e51d0653bdf347ee17d3eb67a/index.js#L14-L16. 

If no callback is passed, it calls the sync function. closing this since it's not a bug here. but, it's arguably not a good idea since we both missed it. which would make it an issue on the other lib. thanks for the feedback

**Closed as completed by jonschlinkert** 2015-03-22 01:54 UTC
Labels: bug
